version: "3.4"
volumes:
  pg-data:
    external: true
networks:
  pg-net:
services:
  pg:
    image: postgres:14.5-alpine
    container_name: pg
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
      - <<backups path>>:/var/lib/postgresql/backups
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - 8002:5432
    networks:
      - pg-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 8003:80
    volumes:
      - <<storage path>>:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: <<email>>@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    networks:
      - pg-net
