version: "3.4"
volumes:
  pg-data:
    external: true
networks:
  pg-net:
    external:
      name: pg-net
services:
  pg:
    image: postgres:14.5-alpine
    container_name: pg
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
      - /storage/pg/backups/db:/var/lib/postgresql/backups
    environment:
      POSTGRES_PASSWORD: pg-password
    ports:
      - 8002:5432
    networks:
      - pg-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - 8003:80
    volumes:
    # owner should be the pgadmin user (UID: 5050) in the pgadmin group (GID: 5050). # chown -R 5050:5050 /storage/pgadmin  
      - /storage/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: some@gmail.com
      PGADMIN_DEFAULT_PASSWORD: agadmin-password
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    networks:
      - pg-net
