version: "3"
services:
  elasticsearch:
    restart: unless-stopped
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: es
    environment:
      - cluster.name=es
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      #- ES_JAVA_OPTS=-Xms4g -Xmx4g
    #mem_limit: 6g
    #memswap_limit: 6g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    restart: unless-stopped
    image: docker.elastic.co/kibana/kibana:7.4.1
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - esnet
volumes:
  esdata:
    driver: local
networks:
  esnet:
