global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    datacenter: dc1

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ["node-exporter:9100"]
        labels:
          host: host1
          service: node
    relabel_configs: &relabelConfigs
      - source_labels: ["host", "service"]
        target_label: instance
        regex: ^(.*);(.*)$
        replacement: "${1}:${2}"

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
        labels:
          host: host1
          service: prometheus
    relabel_configs: *relabelConfigs

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          host: host1
          service: cadvisor
    relabel_configs: *relabelConfigs

  - job_name: grafana
    static_configs:
      - targets: ["grafana:3000"]
        labels:
          host: host1
          service: grafana
    relabel_configs: *relabelConfigs
