version: "3.4"

services:
  centos0:
    image: sandbox
    container_name: centos0
    ports:
      - "49100:22"
  centos1:
    image: sandbox
    container_name: centos1
    ports:
      - "49101:22"
  centos2:
    image: sandbox
    container_name: centos2
    ports:
      - "49102:22"
  centos3:
    image: sandbox
    container_name: centos3
    ports:
      - "49103:22"
