version: "3.4"
services:
  jenkins:
    image: jenkins/jenkins:alpine
    container_name: jenkins
    restart: unless-stopped
    volumes:
      - jenkins_data:/var/jenkins_home
    ports:
      - 8080:8080
    networks:
      - frontend
volumes:
  jenkins_data: {}
networks:
  frontend:
    external:
      name: frontend
