version: "3.4"

services:
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /app/nginx:/app/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    command: '/bin/sh -c ''while :; do sleep 6h; nginx -s reload; done & nginx -g "daemon off;"'''
networks:
  frontend:
    external:
      name: frontend
