version: "3.4"

services:
  proxy:
    restart: unless-stopped
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - frontend
networks:
  frontend:
    external:
      name: frontend
