version: "3.4"

services:
  nginx:
    restart: unless-stopped
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /app/tenogy/:/app/tenogy/
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/nginx/ssl/dhparam.pem:/etc/nginx/ssl/dhparam.pem
    ports:
      - 80:80
      - 443:443
    networks:
      - frontend
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
networks:
  frontend:
    external:
      name: frontend
